Issue #2: Create JDBC Client
sentrysoftware/jdbc pull request #3
Opened 2024-09-25 09:56 UTC by SafaeAJ

Created JdbcClient, DriverLoader and SqlResult
Added Unit Tests.
Updated pom.xm, index.md and README.md

Tested with MySQL and H2 databases.

![Capture d'écran 2024-09-25 113517](https://github.com/user-attachments/assets/7a787e5c-f72c-435c-8dd5-8f473b684d57)
![Capture d'écran 2024-09-25 111744](https://github.com/user-attachments/assets/a295cb1a-79f4-48af-becf-09f0b07a0443)
![Capture d'écran 2024-09-25 114739](https://github.com/user-attachments/assets/59de3c64-8888-43b6-a667-c6a56d99b793)

2024-09-25 10:38 UTC, NassimBtk requested changes

2024-09-25 10:38 UTC, NassimBtk commented on pom.xml
> +	<name>jdbc</name>
`<name>JDBC Client</name>`

2024-09-25 10:38 UTC, NassimBtk commented on pom.xml
> +	<url>https://github.com/sentrysoftware/jdbc</url>
`<url>https://sentrysoftware.org/jdbc</url>`

2024-09-25 10:38 UTC, NassimBtk commented on pom.xml
> +		<url>https://github.com/sentrysoftware/jdbc</url>
`<url>https://sentrysoftware.org/jdbc</url>`

2024-09-25 10:38 UTC, NassimBtk commented on README.md
>  ![GitHub release (with filter)](https://img.shields.io/github/v/release/sentrysoftware/oss-maven-template)
Update all the urls here please.

2024-09-25 10:38 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/jdbc/DriverLoader.java
> +	public static List<String> getLoadeddrivers() {
Javadoc please.

2024-09-25 10:38 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/jdbc/SqlResult.java
> +public class SqlResult {
Add javadoc please.

2024-09-25 10:38 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/jdbc/SqlResult.java
> +	public StringBuilder getWarnings() {
Create `appendWarnings(final String message)`. and manage the "Warning: " prefix in the new  method`appendWarnings(final String message)`.

2024-09-25 10:38 UTC, NassimBtk commented on src/site/markdown/index.md
> +        if (results.getWarnings().length() > 0) {
We can create `results.hasWarnings()`.

2024-09-25 10:38 UTC, NassimBtk commented on pom.xml
>  	<version>0.1.00-SNAPSHOT</version>
`<version>1.0.00-SNAPSHOT</version>`

2024-09-25 10:38 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/jdbc/DriverLoader.java
> +	private static final List<String> loadedDrivers = Collections.synchronizedList(new ArrayList<>());
Should be `LOADED_DRIVERS`.

2024-09-25 10:38 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/jdbc/DriverLoader.java
> +			disableLogging(driverClassName);
Not sure if we should disable logging here. This can be called before loadDriver in matsya 😉

2024-09-25 10:38 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/jdbc/DriverLoader.java
> +	private void disableLogging(String driverClassName) {
should be public static

2024-09-25 10:41 UTC, NassimBtk requested changes

2024-09-25 10:41 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/jdbc/JdbcClient.java
> +  private static void loadDriverForUrl(String url) throws SQLException {
This should be moved to DriverLoader as public method.

2024-09-25 10:41 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/jdbc/JdbcClient.java
> +    loadDriverForUrl(url);
We shouldn't call `loadDriverForUrl(url);` here. The user will load the appropriate driver before executing the request through DriverLoader.

2024-09-25 15:12 UTC, NassimBtk reviewed
Use the same logo as on  https://github.com/sentrysoftware/snmp/tree/main/src/site/resources/images and update site.xml accordingly.

2024-09-26 08:41 UTC, CherfaElyes commented on src/site/site.xml
> +		<keywords>open source, jdbc</keywords>
Please remove `open source` from the keywords as it does not appear in the other clients.

2024-09-26 08:43 UTC, CherfaElyes commented on src/site/site.xml
>  	<body>
in the "User Documentation" menu, please add the following item after `Getting Started` item:
`<item name="Javadoc" href="apidocs/index.html" />`

2024-09-26 08:48 UTC, CherfaElyes commented on src/site/site.xml
>  	</skin>
To confirm with @NassimBtk, sentry-maven-skin latest version is 6.4.01

2024-09-27 15:41 UTC, NassimBtk approved these changes

2024-09-27 15:42 UTC, merged